---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

# EDUCATION BACKGROUND 

##### China Pharmaceutical University, 09/2015 - 06/2019 
- Degree: Bachelor of Management, Business Management; GPA: 3.34/4.0 
- Core Curriculum: Management, Linear Algebra, Economics, Operational Research, Pharmaceutics, Pharmacoeconomics

##### Columbia University, 09/2019 - present 

- Degree: Mater of Science in Biostatistics, Theory and Methods track; GPA: 3.67/4.0 
- Core Curriculum: Data science, Biostatistical Methods, Statistical Inference, Epidemiology

# PROJECT EXPERIENCE 

##### Drug Related Death in Connecticut, Oct 2019 - Dec 2019

- Course Data Science

- Collected drug abuse data in the state of Connecticut; Use R to clean, pivot, and transform data as desired;
- Visualize the geo data of drug abuse along with reference information on the interactive state map.

##### Interpretation of the New Normal Economic Situation, Mar 2017 - Jun 2017

- Course Statistics Principles

- Collected the GDP data, industrial structure, employment personnel, population data of China with python from World Bank Group, outlined main characteristics of the Economy by fulfilling exploratory data analysis. 
- Adopted subdivision analysis and comparative analysis to predict the potential opportunities and changes brought by the new normal economy. 

##### Research on Pharmaceutical Care in Jiangsu Primary Medical Institutions, Jun 2016 - Dec 2016

- Visited and conducted questionnaires with deans, attending doctors, pharmaceutical personnel and patients at five hospitals in Changzhou City, Jiangsu Province 
- Inquired the basic medical facilities, drug reserve and usage (mainly about antibiotics), patient distribution, patients’ understanding of the national drug subsidy policy, and the salary status of pharmaceutical personnel, so as to provide data support for the realization of comprehensive pharmaceutical care in China. 

# WORKING EXPERIENCE

##### Research Technician/Summer Intern; NYSPI and Columbia University Department of Psychiatry, Jun 2020 - present



##### Finance Officer; CUMC Data Science Club, Oct 2019 - present

- Responsible for overseeing the finances and budget of the club; 
- Other delegated work; 

##### Assistant to CEO; CUG Golden Shield Environmental Technology, Feb 2019 - Jun 2019

- Assists the CEO with daily administrative duties; Translate necessary documents; Utilize Excel skills;
- Search for industry information from various sources and drafts report.

##### Student Assistant; China Pharmaceutical University, Sept 2017 - Jun 2019

- Responsible for hosting class meetings; 
- Contact with teachers and arrange office hour; 

# AWARDS 

- The First Prize of the Seventh Securities Investment Preliminary Contest, held by School of Business at CPU, Jun 2018 
- Third-class Scholarship for Merited Students, offered by CPU, Mar 2018 
- The Honorable Title of Excellent Student in 2018, awarded by Nanjing Global Education Co., Ltd, Mar 2018 
- The Honorable Title of Excellent Outstanding Volunteer at Jiangsu Development Summit, offered by Jiangsu Students’ Federation, May 2017 

# ACTIVITIES

- Attendee, 21st Public Health Education Initiative for Chinese Medical Students open course entitled **Medical Innovation in the Era of Digital Intelligence**, Jun 2018 
- Attendee, Global Health Course-China entitled **Global Disasters and Humanitarian Crisis**, Nov 2018 

# SKILLS

## Programming and Softwares: 

Visual Basic, Python, R, SQL; SPSS, MS Office, RStudio(.Rmd), Sublime Text

## Skillsets: 

Visualization, Data Cleaning, strategic and critical thinking, information searching, interpersonal skills 

##### Coursera: 

- Python for Everybody, delivered by the University of Michigan, Aug 2018 - Nov 2018 

- R-Programming, delivered by the Johns Hopkins University, Nov 2018 - Dec 2018 