---
title: "Training"
output: 
  html_document:
    toc: true
    toc_float: true
---

I spent 4 years in business school at China Pharmaceutical University, where I was trained to think critically and utilize quantitative skills in real world problems. Economics and operation research course experience had give me the capability to think and tackle problems quantitively and logially. In course statistics principles, I was able to find the beauty of programming, which inspired me into getting a master's degree where I can learn both statistical methods and programming skills. 

Now I am pursuing my master's degree in Biostatistics at Columbia University. After completing courses such as Data Science and Probability, I have gained/enriched my knowledge in R programming, hypothesis testing, beyesian methods, etc. 

This semester, spring 2020, I am taking courses in Data Science II, which is mostly about machine learning using R. I am actively preparing for my CFA level I exams and SAS exams, also actively looking for summer intern opportunity in the next few months. 